<a href="https://colab.research.google.com/github/sailajarani/pyhton/blob/main/numpy_practice_w3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To get version of numpy

In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


In [ ]:
print(help(np.add))

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array o

In [ ]:
print(np.info(np.add))

None


 Write a NumPy program to test whether none of the elements of a given array is zero.

In [ ]:
arr = np.array([1,2,3,4,5])
arr1 = np.array([2,1,0,2])
print(np.all(arr))
print(np.all(arr1))

True
False


Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [ ]:
print(np.any(arr))
print(np.any(arr1))

True
True


 Write a NumPy program to test a given array element-wise for finiteness

In [ ]:
print(np.isfinite(arr))
print(np.isfinite(arr1))
arr2 = np.array([1,2,np.nan])
print(np.isfinite(arr2))

[ True  True  True  True  True]
[ True  True  True  True]
[ True  True False]


 Write a NumPy program to test element-wise for positive or negative infinity

In [ ]:
print(np.isinf(arr))

[False False False False False]


Write a NumPy program to test element-wise for NaN of a given array

In [ ]:
print(np.isnan(arr))
print(np.isnan(arr1))
print(np.isnan(arr2))

[False False False False False]
[False False False False]
[False False  True]


 Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [ ]:
print(np.iscomplex(arr))
print(np.isreal(arr))
print(np.isscalar(arr))
print(np.isscalar(3))

[False False False False False]
[ True  True  True  True  True]
False
True


 Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [ ]:
print(arr1 == arr)
#print(np.allclose(arr1,arr))
a = np.array([1,2,3,4])
b = np.array([3,4,5,6])
c = np.array([3,4,5,6])
print(np.allclose(a,b))
print(np.allclose(c,b))

False
False
True


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [ ]:
print(np.greater(a,b))
print(np.less(a,b))

[False False False False]
[ True  True  True  True]


Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [ ]:
print(np.equal(a,b))
print(np.equal(b,c))
print(np.allclose(a,c))

[False False False False]
[ True  True  True  True]
False


Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [ ]:

arr = np.array([1,7,13,105])
print(arr.size)  # number of elements in array
print(arr.itemsize) 
print(arr.itemsize * arr.size) #size of memory by whole array

4
8
32


 Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

In [ ]:
print(np.ones(10))
print(np.zeros(10))
print(np.ones(10)*5)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


 Write a NumPy program to create an array of the integers from 30 to70

In [ ]:
print(np.arange(30,71))

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


 Write a NumPy program to create an array of all the even integers from 30 to 70

In [ ]:
print(np.arange(30,71,2))

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Write a NumPy program to create a 3x3 identity matrix

In [ ]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


 Write a NumPy program to generate a random number between 0 and 1

In [ ]:
print(np.random.random())  # gives positive random values only in 0 to 1 

0.21856756045486248


In [ ]:
np.random.random(5)

array([0.45961994, 0.81835921, 0.37847351, 0.09055833, 0.68947989])

In [ ]:
np.random.normal()  #normal gives both positive and negative random values

0.9910768065550593

In [ ]:
np.random.normal(0,1)

-2.579944654925363

In [ ]:
np.random.normal(0,1,1)

array([-1.3360049])

In [ ]:
np.random.normal(0,1,3) #gives a array with 3 values

array([-0.09043038, -1.03394462,  0.16609954])

In [ ]:
np.random.normal(5) # gives one value less than 5

3.685264196503417

 Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [ ]:
print(np.random.normal(0,1,15))

[-1.29180669  0.22577975  0.41007581  1.01708286  0.46434909 -2.47438435
 -0.17098353 -0.16732331  0.19806196  1.29805139 -3.7185949   0.48634147
 -0.47219322  0.03532365  1.1570951 ]


Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last

In [ ]:
vector = np.arange(15,55)
print(vector)
print(vector[1:-1]) # except the first and last



[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


Write a NumPy program to create a 3X4 array using and iterate over it.

In [ ]:
import numpy as np
a = np.arange(10,22).reshape(3, 4)
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
  print(x)
for x in np.nditer(a):
  print(x,end =' ')
print('\n')
for x in a:
  print(x)

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10
11
12
13
14
15
16
17
18
19
20
21
10 11 12 13 14 15 16 17 18 19 20 21 

[10 11 12 13]
[14 15 16 17]
[18 19 20 21]


Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50

In [ ]:
print(np.arange(5,51,5))

[ 5 10 15 20 25 30 35 40 45 50]


Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15

In [ ]:

x = np.arange(21)
print("Original vector:")
print(x)
print("After changing the sign of the numbers in the range from 9 to 15:")
x[(x >= 9) & (x <= 15)] *= -1
print(x)


Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10

In [ ]:
print(np.random.randint(0,10,5))

[0 0 9 9 8]



 Write a NumPy program to multiply the values of two given vectors.

In [ ]:
a = np.arange(0,10)
b = np.arange(10,20)
c = a*b
print(c)

[  0  11  24  39  56  75  96 119 144 171]


 Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21

In [ ]:
arr = np.arange(10,22).reshape((3,4))
print(arr)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


know these difference of random in numpy

In [ ]:
np.arange(10) # 10 is default stopping value..stoppinng value with step 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2,9) # 2 is start and 9 is ending value

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.arange(3,30,3) # 3 is start,30 is endding point,3 is step

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
np.random.rand(5) # It gives 5 random array values between (0,1).

array([0.62151673, 0.38757846, 0.0771684 , 0.15758368, 0.36213854])

In [ ]:
np.random.rand(2,8) #it gives 2 rows 8 columns values.only positive values

array([[[0.14002195, 0.87973925, 0.37232106, 0.38846395, 0.12224418,
         0.72313657],
        [0.01818542, 0.22447161, 0.09288807, 0.32303813, 0.62091785,
         0.76548099],
        [0.0272321 , 0.71360531, 0.19225137, 0.46170049, 0.99844396,
         0.19904688],
        [0.15761722, 0.30695529, 0.99406048, 0.3123055 , 0.45423159,
         0.34050292],
        [0.92809297, 0.20915174, 0.59541043, 0.84972545, 0.61407699,
         0.93457861],
        [0.11638795, 0.21558536, 0.02490597, 0.07322857, 0.97730977,
         0.37654948],
        [0.75993074, 0.21977737, 0.57906046, 0.00478194, 0.16444673,
         0.34197716],
        [0.25044161, 0.38296394, 0.29017509, 0.26052998, 0.82556314,
         0.61328614]],

       [[0.55737022, 0.30139629, 0.18915019, 0.31693149, 0.45788696,
         0.75734771],
        [0.44236043, 0.39034836, 0.78965077, 0.3888491 , 0.37373608,
         0.85298995],
        [0.92826315, 0.67052942, 0.43448078, 0.55330806, 0.2664717 ,
         0.86060642

In [ ]:
np.random.randint(6) # It gives random integer less than 6 here

4

In [ ]:
np.random.randint(3,8) #if it two values then first one is start one,second one is ending value

6

In [ ]:
np.random.randint(3,30,2) # it gives 2 values in the range (3,30)

array([21, 10])

In [ ]:
np.random.randn(5) # IT can gives positive and negative values too,the values may be need not include (0,1),it may be more than that.

array([-5.65816206e-01,  7.36702949e-04, -2.55674404e-01,  1.41893659e-01,
       -7.65061144e-01])

In [ ]:
np.random.randn(3,5) 

array([[ 0.6580793 , -0.81190804,  1.76223157, -0.49855468,  0.26811683],
       [-2.09549876, -2.0693759 , -0.9317882 , -0.67314343,  2.54797353],
       [-0.18381641,  0.54439924, -2.11716237,  1.78540845, -0.18877079]])

In [ ]:
np.random.randn(2,8,3)

array([[[-0.0862137 , -0.05519967,  1.82433695],
        [-0.64309796,  0.98361778,  0.27323177],
        [ 2.4773552 ,  1.26884882,  0.20496758],
        [-0.41435459, -0.18709727,  0.46716638],
        [ 1.8242281 ,  0.77866597,  1.3292727 ],
        [-1.81557227,  0.35996944, -0.83871821],
        [ 0.11175211, -0.42958531,  0.28723708],
        [-0.25607713, -0.53982759,  0.2651126 ]],

       [[-1.69387741,  2.1905683 ,  0.06393554],
        [-0.29332432, -1.3527199 ,  0.73609464],
        [ 2.194257  , -0.59424485, -1.60033206],
        [ 0.42439799,  0.33937577, -0.45389196],
        [-1.17128132, -0.6157917 , -0.74128574],
        [ 0.2964685 , -2.35203226, -0.58609507],
        [ 0.79483116,  0.1116475 , -0.40902441],
        [-0.78124631, -0.55398238, -0.48135712]]])

In [ ]:
np.random.random() #it gives random value

0.46679229763919905

In [ ]:
np.random.random(5) #it gives 5 random values

array([0.92647917, 0.23307964, 0.59329447, 0.87250453, 0.82066599])